language: python
python:
- '2.7'
services:
- docker
script:
- true
before_deploy:
- docker build -t oioioi .
deploy:
- provider: script
  script: bash docker_push.sh
  on:
    branch: master
env:
  global:
  - secure: YkJihvKT4MEnPTN/ltJtP2zyq7HUw881dgFzn/zf5dsultds/heeJql3TzsD79eYJCXYpa5bsaHXEph764euEC6x8or6Et/sSHiThGBsaKUpoQpefaEDL59O1+kyipAvZ9Il4wwds4RORmDkaQmqWm4CvmXXMkRcrtZfn9oDB5+IdhxjahA3nYyWdk50yK96Xsrd6OFIj2tI6Scsem33ZgqBjiomUKUUdS8sLmwRSynOZAO2YtGtmcel/oXY9yjp/I3s9xwYdySw7q7Wg9ONcyASX3I4IMwlqVP73Qml/U2T/BlpE2B/ZLeO8Rqzae+oW1OSwoKUJS8n66ACHrPh7Ruplz82r7E2zpF9fjfkcZ/biQDVYSUSZZTEP1UP4CFEw3RR4zIn5a9BKfemQ0SNoLm3VdIbKbvwDfQsWeE/VpSq4rWt4TpbDVvzmvkALebfo+47Ns4mABmfe5WDvprwPDW40CltiPknuPV9q5BobXnCtsgoB97jBZf55Ohdnpn6qAyhWLbbD6IL6zm9+fVwhXvgOxTck698P8QHXe+sK4Oa4B0my4GxqL6tzKj8X9XsqOSCn9Pr9hwc0SydT7JmmAVlRPmmGSvIRJaMdlu2h7a98JyHBp8f8984YduNLyoD5bQkW4S5Ue92msZXpSmz8G2vb86NsOYvRIEKMpTTbWQ=
  - secure: oK6wTPGjkCYjeuQsAe8TEB6UtYNwQShhv/9OWogE5e/HLBnms0sjD2iapC9VTFbUSZaZR7830L2VORn3ZQwYyxa5FQLqIvpDj8/d0zzUSsLeygptLX7QMkvUiFaKPBksTAxPubV1RBl7RmSbz/6A3K97kR6HqxL1xUArCWOAwLw4hSujI7ewAPzj3oxsf4sCP0KRYKoeK5Ff0cAsQG00nne/TtvdWi8vHiDPOzOchNFj3zQkPxpEHyoWJebJGcYVJtCsYogwmTinmBMoVCobRO2ryngwSxOXOYQTK6xT3Tx8xj/1yFAF2k3UqnD27NeGV10mELX/QZ9PFHa5WAjf2olaNfoLZgwQy5UIaWPkY6jLKFgHxQ/P6/xCrIXudjwcoysecK7mFOMuAf5Ov/AfhROmZ3pg3oC2RiJOWtjUdrix6lQZlVW6gS7sBzoPYy5YJCYz+4ir8dZS/3FHnJ0AsKbWID84jq9NAzavDdVcOI+EeLSK+F+PhRJoEQ0XWiOyGl901TQYPyUFvvUM5vluYcuhFw5FXh6WX5YArmF0Bu7Veuw1SWYH7akMEiKTDp3MdmD4EmPfAUW6N42xmpy33c/ZFcNUcsaiCGlH79LJSuLGUqc812IRHWtXJ5zEHQ8VjYWTRybLrFP8ug9JoxvZdoCcFNrM1sJVUSofX3z20Ug=
